@GraduateAppApi = https://localhost:7037
@AccessToken = replace-with-a-development-access-token

GET {{GraduateAppApi}}/api/programs/open
Accept: application/json

###

GET {{GraduateAppApi}}/api/applications/mine
Authorization: Bearer {{AccessToken}}
Accept: application/json
