// <auto-generated />
using System;
using GraduateApp.API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GraduateApp.API.Migrations
{
    [DbContext(typeof(GraduateAppDbContext))]
    partial class GraduateAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GraduateApp.API.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AdminID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminId"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsInvitationPending")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset?>("LockoutEndUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("bit");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .IsUnicode(false)
                        .HasColumnType("varchar(512)");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PublicID");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("AdminId");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("GraduateApp.API.Models.Application", b =>
                {
                    b.Property<int>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ApplicationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApplicationId"));

                    b.Property<DateTime>("ApplicationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending");

                    b.Property<int>("ProgramOfferingId")
                        .HasColumnType("int")
                        .HasColumnName("ProgramOfferingID");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PublicID")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Tc")
                        .IsRequired()
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("char(11)")
                        .HasColumnName("TC")
                        .IsFixedLength();

                    b.Property<bool>("UsesDocumentWorkflow")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("UsesEvaluationWorkflow")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("ApplicationId");

                    b.HasIndex("ProgramOfferingId");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("Tc", "ProgramOfferingId")
                        .IsUnique();

                    b.ToTable("Applications", null, t =>
                        {
                            t.HasCheckConstraint("CK_Applications_CurrentStatus", "[CurrentStatus] IN (N'Draft',N'Pending',N'UnderReview',N'Approved',N'Rejected',N'Withdrawn')");
                        });
                });

            modelBuilder.Entity("GraduateApp.API.Models.ApplicationDocument", b =>
                {
                    b.Property<long>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("DocumentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("DocumentId"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int")
                        .HasColumnName("ApplicationID");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PublicID")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RequirementSnapshotId")
                        .HasColumnType("int")
                        .HasColumnName("RequirementSnapshotID");

                    b.Property<string>("ReviewStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("ReviewedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReviewedByAdminId")
                        .HasColumnType("int")
                        .HasColumnName("ReviewedByAdminID");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .IsFixedLength();

                    b.Property<DateTime>("UploadedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("VerifiedContentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int");

                    b.HasKey("DocumentId");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("ObjectKey")
                        .IsUnique();

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("RequirementSnapshotId")
                        .IsUnique()
                        .HasFilter("[IsCurrent] = CAST(1 AS bit)");

                    b.HasIndex("ReviewedByAdminId");

                    b.HasIndex("RequirementSnapshotId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("ApplicationDocuments", null, t =>
                        {
                            t.HasCheckConstraint("CK_ApplicationDocuments_ContentType", "[VerifiedContentType] IN ('application/pdf','image/jpeg','image/png')");

                            t.HasCheckConstraint("CK_ApplicationDocuments_FileSize", "[FileSize] > 0");

                            t.HasCheckConstraint("CK_ApplicationDocuments_ObjectKey", "LEN([ObjectKey]) = 32 AND [ObjectKey] COLLATE Latin1_General_100_BIN2 NOT LIKE '%[^0-9a-f]%'");

                            t.HasCheckConstraint("CK_ApplicationDocuments_Review", "([ReviewStatus] = 'Rejected' AND [RejectionReason] IS NOT NULL AND LEN(LTRIM(RTRIM([RejectionReason]))) > 0) OR ([ReviewStatus] IN ('Pending','Approved') AND [RejectionReason] IS NULL)");

                            t.HasCheckConstraint("CK_ApplicationDocuments_Sha256", "LEN([Sha256]) = 64 AND [Sha256] COLLATE Latin1_General_100_BIN2 NOT LIKE '%[^0-9a-f]%'");

                            t.HasCheckConstraint("CK_ApplicationDocuments_VersionNumber", "[VersionNumber] > 0");
                        });
                });

            modelBuilder.Entity("GraduateApp.API.Models.ApplicationDocumentRequirementSnapshot", b =>
                {
                    b.Property<int>("SnapshotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SnapshotID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SnapshotId"));

                    b.Property<string>("AllowedContentCategory")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int")
                        .HasColumnName("ApplicationID");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("DocumentCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<long>("MaximumBytes")
                        .HasColumnType("bigint");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PublicID")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int?>("SourceRequirementId")
                        .HasColumnType("int")
                        .HasColumnName("SourceRequirementID");

                    b.HasKey("SnapshotId");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("SourceRequirementId");

                    b.HasIndex("ApplicationId", "DocumentCode")
                        .IsUnique();

                    b.ToTable("ApplicationDocumentRequirementSnapshots", null, t =>
                        {
                            t.HasCheckConstraint("CK_ApplicationDocumentRequirementSnapshots_ContentCategory", "[AllowedContentCategory] IN ('PdfOnly','ImageOnly','PdfOrImage')");

                            t.HasCheckConstraint("CK_ApplicationDocumentRequirementSnapshots_MaximumBytes", "[MaximumBytes] BETWEEN 1 AND 104857600");
                        });
                });

            modelBuilder.Entity("GraduateApp.API.Models.ApplicationEvaluation", b =>
                {
                    b.Property<int>("ApplicationEvaluationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ApplicationEvaluationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApplicationEvaluationId"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int")
                        .HasColumnName("ApplicationID");

                    b.Property<DateTime?>("EligibilityDecidedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EligibilityDecidedByAdminId")
                        .HasColumnType("int")
                        .HasColumnName("EligibilityDecidedByAdminID");

                    b.Property<string>("EligibilityStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("FinalizedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("IneligibilityReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Outcome")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("ProgramOfferingId")
                        .HasColumnType("int")
                        .HasColumnName("ProgramOfferingID");

                    b.Property<int?>("Rank")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal?>("TotalScore")
                        .HasColumnType("decimal(7, 4)");

                    b.HasKey("ApplicationEvaluationId");

                    b.HasIndex("ApplicationId")
                        .IsUnique();

                    b.HasIndex("EligibilityDecidedByAdminId");

                    b.HasIndex("ProgramOfferingId", "Rank")
                        .IsUnique()
                        .HasFilter("[Rank] IS NOT NULL");

                    b.ToTable("ApplicationEvaluations", null, t =>
                        {
                            t.HasCheckConstraint("CK_ApplicationEvaluations_EligibilityStatus", "[EligibilityStatus] IN ('Pending','Eligible','Ineligible')");

                            t.HasCheckConstraint("CK_ApplicationEvaluations_EligibilityDecision", "([EligibilityStatus] = 'Pending' AND [EligibilityDecidedByAdminID] IS NULL AND [EligibilityDecidedAtUtc] IS NULL) OR ([EligibilityStatus] IN ('Eligible','Ineligible') AND [EligibilityDecidedByAdminID] IS NOT NULL AND [EligibilityDecidedAtUtc] IS NOT NULL)");

                            t.HasCheckConstraint("CK_ApplicationEvaluations_FinalResult", "([Outcome] IS NULL AND [Rank] IS NULL AND [FinalizedAtUtc] IS NULL) OR ([Outcome] IN ('Admitted','NotAdmitted') AND [Rank] IS NOT NULL AND [TotalScore] IS NOT NULL AND [FinalizedAtUtc] IS NOT NULL) OR ([Outcome] = 'Ineligible' AND [Rank] IS NULL AND [TotalScore] IS NULL AND [FinalizedAtUtc] IS NOT NULL)");

                            t.HasCheckConstraint("CK_ApplicationEvaluations_IneligibilityReason", "([EligibilityStatus] = 'Ineligible' AND [IneligibilityReason] IS NOT NULL AND LEN(LTRIM(RTRIM([IneligibilityReason]))) > 0) OR ([EligibilityStatus] IN ('Pending','Eligible') AND [IneligibilityReason] IS NULL)");

                            t.HasCheckConstraint("CK_ApplicationEvaluations_Outcome", "[Outcome] IS NULL OR [Outcome] IN ('Admitted','NotAdmitted','Ineligible')");

                            t.HasCheckConstraint("CK_ApplicationEvaluations_Rank", "[Rank] IS NULL OR [Rank] > 0");

                            t.HasCheckConstraint("CK_ApplicationEvaluations_TotalScore", "[TotalScore] IS NULL OR [TotalScore] BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("GraduateApp.API.Models.ApplicationEvaluationComponent", b =>
                {
                    b.Property<int>("ComponentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ComponentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComponentId"));

                    b.Property<int>("ApplicationEvaluationId")
                        .HasColumnType("int")
                        .HasColumnName("ApplicationEvaluationID");

                    b.Property<string>("CodeSnapshot")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<Guid>("CriterionPublicIdSnapshot")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CriterionPublicIDSnapshot");

                    b.Property<string>("DisplayNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("ExamId")
                        .HasColumnType("int")
                        .HasColumnName("ExamID");

                    b.Property<DateTime?>("ManualScoredAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ManualScoredByAdminId")
                        .HasColumnType("int")
                        .HasColumnName("ManualScoredByAdminID");

                    b.Property<decimal>("MaximumRawScoreSnapshot")
                        .HasColumnType("decimal(9, 4)");

                    b.Property<decimal?>("NormalizedScore")
                        .HasColumnType("decimal(7, 4)");

                    b.Property<decimal?>("RawScore")
                        .HasColumnType("decimal(9, 4)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int?>("SourceCriterionId")
                        .HasColumnType("int")
                        .HasColumnName("SourceCriterionID");

                    b.Property<string>("SourceTypeSnapshot")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<int>("TieBreakPrioritySnapshot")
                        .HasColumnType("int");

                    b.Property<int>("WeightBasisPointsSnapshot")
                        .HasColumnType("int");

                    b.Property<decimal?>("WeightedScore")
                        .HasColumnType("decimal(7, 4)");

                    b.HasKey("ComponentId");

                    b.HasIndex("ManualScoredByAdminId");

                    b.HasIndex("SourceCriterionId");

                    b.HasIndex("ApplicationEvaluationId", "CodeSnapshot")
                        .IsUnique();

                    b.HasIndex("ApplicationEvaluationId", "TieBreakPrioritySnapshot")
                        .IsUnique();

                    b.ToTable("ApplicationEvaluationComponents", null, t =>
                        {
                            t.HasCheckConstraint("CK_ApplicationEvaluationComponents_NormalizedScore", "[NormalizedScore] IS NULL OR [NormalizedScore] BETWEEN 0 AND 100");

                            t.HasCheckConstraint("CK_ApplicationEvaluationComponents_ManualAudit", "([ManualScoredByAdminID] IS NULL AND [ManualScoredAtUtc] IS NULL) OR ([SourceTypeSnapshot] = 'ManualScore' AND [ManualScoredByAdminID] IS NOT NULL AND [ManualScoredAtUtc] IS NOT NULL)");

                            t.HasCheckConstraint("CK_ApplicationEvaluationComponents_RawScore", "[RawScore] IS NULL OR ([RawScore] >= 0 AND [RawScore] <= [MaximumRawScoreSnapshot])");

                            t.HasCheckConstraint("CK_ApplicationEvaluationComponents_SourceType", "[SourceTypeSnapshot] IN ('UndergraduateGpa','ExamScore','ManualScore')");

                            t.HasCheckConstraint("CK_ApplicationEvaluationComponents_SourceConfiguration", "([SourceTypeSnapshot] = 'UndergraduateGpa' AND [ExamID] IS NULL AND [MaximumRawScoreSnapshot] = 4) OR ([SourceTypeSnapshot] = 'ExamScore' AND [ExamID] IS NOT NULL AND [MaximumRawScoreSnapshot] > 0) OR ([SourceTypeSnapshot] = 'ManualScore' AND [ExamID] IS NULL AND [MaximumRawScoreSnapshot] = 100)");

                            t.HasCheckConstraint("CK_ApplicationEvaluationComponents_ScoreCompleteness", "([RawScore] IS NULL AND [NormalizedScore] IS NULL AND [WeightedScore] IS NULL) OR ([RawScore] IS NOT NULL AND [NormalizedScore] IS NOT NULL AND [WeightedScore] IS NOT NULL)");

                            t.HasCheckConstraint("CK_ApplicationEvaluationComponents_TieBreak", "[TieBreakPrioritySnapshot] > 0");

                            t.HasCheckConstraint("CK_ApplicationEvaluationComponents_Weight", "[WeightBasisPointsSnapshot] BETWEEN 1 AND 10000");

                            t.HasCheckConstraint("CK_ApplicationEvaluationComponents_WeightedScore", "[WeightedScore] IS NULL OR [WeightedScore] BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("GraduateApp.API.Models.ApplicationScoreSnapshot", b =>
                {
                    b.Property<int>("ApplicationScoreSnapshotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ApplicationScoreSnapshotID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApplicationScoreSnapshotId"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int")
                        .HasColumnName("ApplicationID");

                    b.Property<DateTime>("CapturedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateOnly?>("ExamDateSnapshot")
                        .HasColumnType("date");

                    b.Property<int>("ExamId")
                        .HasColumnType("int")
                        .HasColumnName("ExamID");

                    b.Property<string>("ExamNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("ScoreSnapshot")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("ApplicationScoreSnapshotId");

                    b.HasIndex("ExamId");

                    b.HasIndex("ApplicationId", "ExamId")
                        .IsUnique();

                    b.ToTable("ApplicationScoreSnapshots");
                });

            modelBuilder.Entity("GraduateApp.API.Models.ApplicationStatusHistory", b =>
                {
                    b.Property<int>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("HistoryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistoryId"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int")
                        .HasColumnName("ApplicationID");

                    b.Property<DateTime>("ChangeDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int?>("ChangedByAdminId")
                        .HasColumnType("int")
                        .HasColumnName("ChangedByAdminID");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PreviousStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("HistoryId");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("ChangedByAdminId");

                    b.ToTable("ApplicationStatusHistory", (string)null);
                });

            modelBuilder.Entity("GraduateApp.API.Models.EducationInfo", b =>
                {
                    b.Property<int>("EducationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EducationID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EducationId"));

                    b.Property<string>("DiplomaPath")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Faculty")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("Gno")
                        .HasColumnType("decimal(3, 2)")
                        .HasColumnName("GNO");

                    b.Property<string>("GraduatedProgram")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Tc")
                        .IsRequired()
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("char(11)")
                        .HasColumnName("TC")
                        .IsFixedLength();

                    b.Property<string>("TranscriptPath")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("UniversityId")
                        .HasColumnType("int")
                        .HasColumnName("UniversityID");

                    b.HasKey("EducationId");

                    b.HasIndex("Tc");

                    b.HasIndex("UniversityId");

                    b.ToTable("EducationInfo", (string)null);
                });

            modelBuilder.Entity("GraduateApp.API.Models.Exam", b =>
                {
                    b.Property<int>("ExamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ExamID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExamId"));

                    b.Property<string>("ExamName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ExamId");

                    b.HasIndex("ExamName")
                        .IsUnique();

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("GraduateApp.API.Models.Institute", b =>
                {
                    b.Property<int>("InstituteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("InstituteID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InstituteId"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("InstituteName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("InstituteId");

                    b.HasIndex("InstituteName")
                        .IsUnique();

                    b.ToTable("Institutes", null, t =>
                        {
                            t.HasCheckConstraint("CK_Institutes_InstituteName_Trimmed", "[InstituteName] = LTRIM(RTRIM([InstituteName])) AND LEN([InstituteName]) >= 2");
                        });
                });

            modelBuilder.Entity("GraduateApp.API.Models.LoginIdentity", b =>
                {
                    b.Property<int>("LoginIdentityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LoginIdentityID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoginIdentityId"));

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("AdminId")
                        .HasColumnType("int")
                        .HasColumnName("AdminID");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("StudentTc")
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("char(11)")
                        .HasColumnName("StudentTC")
                        .IsFixedLength();

                    b.HasKey("LoginIdentityId");

                    b.HasIndex("AdminId")
                        .IsUnique()
                        .HasFilter("[AdminID] IS NOT NULL");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.HasIndex("StudentTc")
                        .IsUnique()
                        .HasFilter("[StudentTC] IS NOT NULL");

                    b.ToTable("LoginIdentities", null, t =>
                        {
                            t.HasCheckConstraint("CK_LoginIdentities_Subject", "([AccountType] = N'Student' AND [StudentTC] IS NOT NULL AND [AdminID] IS NULL) OR ([AccountType] = N'Admin' AND [StudentTC] IS NULL AND [AdminID] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("GraduateApp.API.Models.PasswordResetToken", b =>
                {
                    b.Property<int>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TokenID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TokenId"));

                    b.Property<int?>("AdminId")
                        .HasColumnType("int")
                        .HasColumnName("AdminID");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasDefaultValue("PasswordReset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Tc")
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("char(11)")
                        .HasColumnName("TC")
                        .IsFixedLength();

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("varchar(256)");

                    b.HasKey("TokenId");

                    b.HasIndex("AdminId");

                    b.HasIndex("Tc");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("PasswordResetTokens", null, t =>
                        {
                            t.HasCheckConstraint("CK_PasswordResetTokens_Purpose", "[Purpose] IN (N'PasswordReset', N'AdminInvitation') AND ([Purpose] <> N'AdminInvitation' OR [AdminID] IS NOT NULL)");

                            t.HasCheckConstraint("CK_PasswordResetTokens_Subject", "([TC] IS NOT NULL AND [AdminID] IS NULL) OR ([TC] IS NULL AND [AdminID] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("GraduateApp.API.Models.Program", b =>
                {
                    b.Property<int>("ProgramId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProgramID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProgramId"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("DegreeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("InstituteId")
                        .HasColumnType("int")
                        .HasColumnName("InstituteID");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("ProgramName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("ProgramId");

                    b.HasIndex("InstituteId", "ProgramName", "DegreeType")
                        .IsUnique();

                    b.ToTable("Programs", null, t =>
                        {
                            t.HasCheckConstraint("CK_Programs_DegreeType", "[DegreeType] IN (N'Doktora',N'Tezli Yüksek Lisans',N'Tezsiz Yüksek Lisans',N'Uzaktan Tezsiz Yüksek Lisans')");

                            t.HasCheckConstraint("CK_Programs_ProgramName_Trimmed", "[ProgramName] = LTRIM(RTRIM([ProgramName])) AND LEN([ProgramName]) >= 2");
                        });
                });

            modelBuilder.Entity("GraduateApp.API.Models.ProgramOffering", b =>
                {
                    b.Property<int>("ProgramOfferingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProgramOfferingID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProgramOfferingId"));

                    b.Property<int>("AcademicYearStart")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ApplicationDeadlineUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ApplicationStartUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<DateTime?>("EvaluationFinalizedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("EvaluationState")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Configuring");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("bit");

                    b.Property<int>("ProgramId")
                        .HasColumnType("int")
                        .HasColumnName("ProgramID");

                    b.Property<int>("Quota")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ResultsPublishedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Term")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<bool>("UsesEvaluationWorkflow")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("ProgramOfferingId");

                    b.HasIndex("ProgramId", "AcademicYearStart", "Term")
                        .IsUnique();

                    b.ToTable("ProgramOfferings", null, t =>
                        {
                            t.HasCheckConstraint("CK_ProgramOfferings_AcademicPeriod", "([AcademicYearStart] = 0 AND [Term] = 0) OR ([AcademicYearStart] BETWEEN 2000 AND 2200 AND [Term] IN (1,2,3))");

                            t.HasCheckConstraint("CK_ProgramOfferings_DateRange", "[ApplicationStartUtc] IS NULL OR [ApplicationDeadlineUtc] IS NULL OR [ApplicationStartUtc] < [ApplicationDeadlineUtc]");

                            t.HasCheckConstraint("CK_ProgramOfferings_EvaluationState", "[EvaluationState] IN ('Configuring','Finalized','Published')");

                            t.HasCheckConstraint("CK_ProgramOfferings_EvaluationLifecycle", "([EvaluationState] = 'Configuring' AND [EvaluationFinalizedAtUtc] IS NULL AND [ResultsPublishedAtUtc] IS NULL) OR ([EvaluationState] = 'Finalized' AND [EvaluationFinalizedAtUtc] IS NOT NULL AND [ResultsPublishedAtUtc] IS NULL) OR ([EvaluationState] = 'Published' AND [EvaluationFinalizedAtUtc] IS NOT NULL AND [ResultsPublishedAtUtc] IS NOT NULL)");

                            t.HasCheckConstraint("CK_ProgramOfferings_Quota", "[Quota] >= 0");
                        });
                });

            modelBuilder.Entity("GraduateApp.API.Models.ProgramOfferingDocumentRequirement", b =>
                {
                    b.Property<int>("RequirementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RequirementID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequirementId"));

                    b.Property<string>("AllowedContentCategory")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("DocumentCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<long>("MaximumBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("NormalizedDocumentCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("ProgramOfferingId")
                        .HasColumnType("int")
                        .HasColumnName("ProgramOfferingID");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PublicID")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("RequirementId");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("ProgramOfferingId", "NormalizedDocumentCode")
                        .IsUnique();

                    b.ToTable("ProgramOfferingDocumentRequirements", null, t =>
                        {
                            t.HasCheckConstraint("CK_ProgramOfferingDocumentRequirements_ContentCategory", "[AllowedContentCategory] IN ('PdfOnly','ImageOnly','PdfOrImage')");

                            t.HasCheckConstraint("CK_ProgramOfferingDocumentRequirements_MaximumBytes", "[MaximumBytes] BETWEEN 1 AND 104857600");
                        });
                });

            modelBuilder.Entity("GraduateApp.API.Models.ProgramOfferingEvaluationCriterion", b =>
                {
                    b.Property<int>("CriterionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CriterionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CriterionId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("ExamId")
                        .HasColumnType("int")
                        .HasColumnName("ExamID");

                    b.Property<decimal>("MaximumRawScore")
                        .HasColumnType("decimal(9, 4)");

                    b.Property<string>("NormalizedCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("ProgramOfferingId")
                        .HasColumnType("int")
                        .HasColumnName("ProgramOfferingID");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PublicID")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<int>("TieBreakPriority")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("WeightBasisPoints")
                        .HasColumnType("int");

                    b.HasKey("CriterionId");

                    b.HasIndex("ExamId");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("ProgramOfferingId", "ExamId")
                        .IsUnique()
                        .HasFilter("[ExamID] IS NOT NULL");

                    b.HasIndex("ProgramOfferingId", "NormalizedCode")
                        .IsUnique();

                    b.HasIndex("ProgramOfferingId", "SourceType")
                        .IsUnique()
                        .HasFilter("[SourceType] = 'UndergraduateGpa'");

                    b.HasIndex("ProgramOfferingId", "TieBreakPriority")
                        .IsUnique();

                    b.ToTable("ProgramOfferingEvaluationCriteria", null, t =>
                        {
                            t.HasCheckConstraint("CK_ProgramOfferingEvaluationCriteria_Code", "[Code] = LTRIM(RTRIM([Code])) AND LEN([Code]) BETWEEN 2 AND 64");

                            t.HasCheckConstraint("CK_ProgramOfferingEvaluationCriteria_SourceConfiguration", "([SourceType] = 'UndergraduateGpa' AND [ExamID] IS NULL AND [MaximumRawScore] = 4) OR ([SourceType] = 'ExamScore' AND [ExamID] IS NOT NULL AND [MaximumRawScore] > 0) OR ([SourceType] = 'ManualScore' AND [ExamID] IS NULL AND [MaximumRawScore] = 100)");

                            t.HasCheckConstraint("CK_ProgramOfferingEvaluationCriteria_SourceType", "[SourceType] IN ('UndergraduateGpa','ExamScore','ManualScore')");

                            t.HasCheckConstraint("CK_ProgramOfferingEvaluationCriteria_TieBreak", "[TieBreakPriority] > 0");

                            t.HasCheckConstraint("CK_ProgramOfferingEvaluationCriteria_Weight", "[WeightBasisPoints] BETWEEN 1 AND 10000");
                        });
                });

            modelBuilder.Entity("GraduateApp.API.Models.ProgramOfferingExamRequirement", b =>
                {
                    b.Property<int>("RequirementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RequirementID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequirementId"));

                    b.Property<int>("ExamId")
                        .HasColumnType("int")
                        .HasColumnName("ExamID");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<decimal>("MinimumScore")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<DateOnly?>("MinimumValidityDate")
                        .HasColumnType("date");

                    b.Property<int>("ProgramOfferingId")
                        .HasColumnType("int")
                        .HasColumnName("ProgramOfferingID");

                    b.HasKey("RequirementId");

                    b.HasIndex("ExamId");

                    b.HasIndex("ProgramOfferingId", "ExamId")
                        .IsUnique();

                    b.ToTable("ProgramOfferingExamRequirements", null, t =>
                        {
                            t.HasCheckConstraint("CK_ProgramOfferingExamRequirements_MinimumScore", "[MinimumScore] >= 0");
                        });
                });

            modelBuilder.Entity("GraduateApp.API.Models.ReferenceLetter", b =>
                {
                    b.Property<int>("ReferenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ReferenceID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReferenceId"));

                    b.Property<string>("AcademicianEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("AcademicianName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int")
                        .HasColumnName("ApplicationID");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ReferenceId");

                    b.HasIndex("ApplicationId");

                    b.ToTable("ReferenceLetters");
                });

            modelBuilder.Entity("GraduateApp.API.Models.SecurityAuditLog", b =>
                {
                    b.Property<long>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AuditId"));

                    b.Property<int?>("ActorAdminId")
                        .HasColumnType("int")
                        .HasColumnName("ActorAdminID");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Details")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AuditId");

                    b.HasIndex("CreatedAtUtc");

                    b.ToTable("SecurityAuditLogs");
                });

            modelBuilder.Entity("GraduateApp.API.Models.Student", b =>
                {
                    b.Property<string>("Tc")
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("char(11)")
                        .HasColumnName("TC")
                        .IsFixedLength();

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("FatherName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTimeOffset?>("LockoutEndUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .IsUnicode(false)
                        .HasColumnType("varchar(512)");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PublicID")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StudentSurname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telephone")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Tc");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("Telephone")
                        .IsUnique()
                        .HasFilter("[Telephone] IS NOT NULL");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("GraduateApp.API.Models.StudentExamScore", b =>
                {
                    b.Property<int>("ScoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ScoreID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScoreId"));

                    b.Property<DateOnly?>("ExamDate")
                        .HasColumnType("date");

                    b.Property<int>("ExamId")
                        .HasColumnType("int")
                        .HasColumnName("ExamID");

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("Tc")
                        .IsRequired()
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("char(11)")
                        .HasColumnName("TC")
                        .IsFixedLength();

                    b.HasKey("ScoreId");

                    b.HasIndex("ExamId");

                    b.HasIndex("Tc", "ExamId")
                        .IsUnique();

                    b.ToTable("StudentExamScores");
                });

            modelBuilder.Entity("GraduateApp.API.Models.SystemLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LogID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("AdminId")
                        .HasColumnType("int")
                        .HasColumnName("AdminID");

                    b.Property<DateTime?>("LogDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("LogDetails")
                        .HasColumnType("xml");

                    b.Property<string>("Tc")
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("char(11)")
                        .HasColumnName("TC")
                        .IsFixedLength();

                    b.HasKey("LogId");

                    b.HasIndex("AdminId");

                    b.HasIndex("Tc");

                    b.ToTable("SystemLogs");
                });

            modelBuilder.Entity("GraduateApp.API.Models.University", b =>
                {
                    b.Property<int>("UniversityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UniversityID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UniversityId"));

                    b.Property<string>("UniversityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UniversityId");

                    b.HasIndex("UniversityName")
                        .IsUnique();

                    b.ToTable("Universities");
                });

            modelBuilder.Entity("GraduateApp.API.Models.VwAdminApplicationSummary", b =>
                {
                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasMaxLength(101)
                        .HasColumnType("nvarchar(101)");

                    b.Property<int>("BasvuruNo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("BasvuruTarihi")
                        .HasColumnType("datetime");

                    b.Property<string>("Enstitu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GuncelDurum")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("KimlikNo")
                        .IsRequired()
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("char(11)")
                        .IsFixedLength();

                    b.Property<decimal?>("LisansOrtalamasi")
                        .HasColumnType("decimal(3, 2)");

                    b.Property<string>("MezunOlduguUniversite")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Program")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.ToTable((string)null);

                    b.ToView("vw_AdminApplicationSummary", (string)null);
                });

            modelBuilder.Entity("GraduateApp.API.Models.Application", b =>
                {
                    b.HasOne("GraduateApp.API.Models.ProgramOffering", "ProgramOffering")
                        .WithMany("Applications")
                        .HasForeignKey("ProgramOfferingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GraduateApp.API.Models.Student", "TcNavigation")
                        .WithMany("Applications")
                        .HasForeignKey("Tc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProgramOffering");

                    b.Navigation("TcNavigation");
                });

            modelBuilder.Entity("GraduateApp.API.Models.ApplicationDocument", b =>
                {
                    b.HasOne("GraduateApp.API.Models.Application", "Application")
                        .WithMany("Documents")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GraduateApp.API.Models.ApplicationDocumentRequirementSnapshot", "RequirementSnapshot")
                        .WithMany("Documents")
                        .HasForeignKey("RequirementSnapshotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GraduateApp.API.Models.Admin", "ReviewedByAdmin")
                        .WithMany("ReviewedApplicationDocuments")
                        .HasForeignKey("ReviewedByAdminId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Application");

                    b.Navigation("RequirementSnapshot");

                    b.Navigation("ReviewedByAdmin");
                });

            modelBuilder.Entity("GraduateApp.API.Models.ApplicationDocumentRequirementSnapshot", b =>
                {
                    b.HasOne("GraduateApp.API.Models.Application", "Application")
                        .WithMany("DocumentRequirementSnapshots")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GraduateApp.API.Models.ProgramOfferingDocumentRequirement", "SourceRequirement")
                        .WithMany("Snapshots")
                        .HasForeignKey("SourceRequirementId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Application");

                    b.Navigation("SourceRequirement");
                });

            modelBuilder.Entity("GraduateApp.API.Models.ApplicationEvaluation", b =>
                {
                    b.HasOne("GraduateApp.API.Models.Application", "Application")
                        .WithOne("Evaluation")
                        .HasForeignKey("GraduateApp.API.Models.ApplicationEvaluation", "ApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GraduateApp.API.Models.Admin", "EligibilityDecidedByAdmin")
                        .WithMany()
                        .HasForeignKey("EligibilityDecidedByAdminId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GraduateApp.API.Models.ProgramOffering", "ProgramOffering")
                        .WithMany()
                        .HasForeignKey("ProgramOfferingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("EligibilityDecidedByAdmin");

                    b.Navigation("ProgramOffering");
                });

            modelBuilder.Entity("GraduateApp.API.Models.ApplicationEvaluationComponent", b =>
                {
                    b.HasOne("GraduateApp.API.Models.ApplicationEvaluation", "ApplicationEvaluation")
                        .WithMany("Components")
                        .HasForeignKey("ApplicationEvaluationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GraduateApp.API.Models.Admin", "ManualScoredByAdmin")
                        .WithMany()
                        .HasForeignKey("ManualScoredByAdminId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GraduateApp.API.Models.ProgramOfferingEvaluationCriterion", "SourceCriterion")
                        .WithMany("Components")
                        .HasForeignKey("SourceCriterionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ApplicationEvaluation");

                    b.Navigation("ManualScoredByAdmin");

                    b.Navigation("SourceCriterion");
                });

            modelBuilder.Entity("GraduateApp.API.Models.ApplicationScoreSnapshot", b =>
                {
                    b.HasOne("GraduateApp.API.Models.Application", "Application")
                        .WithMany("ScoreSnapshots")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GraduateApp.API.Models.Exam", "Exam")
                        .WithMany("ApplicationScoreSnapshots")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("GraduateApp.API.Models.ApplicationStatusHistory", b =>
                {
                    b.HasOne("GraduateApp.API.Models.Application", "Application")
                        .WithMany("ApplicationStatusHistories")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GraduateApp.API.Models.Admin", "ChangedByAdmin")
                        .WithMany("ApplicationStatusHistories")
                        .HasForeignKey("ChangedByAdminId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Application");

                    b.Navigation("ChangedByAdmin");
                });

            modelBuilder.Entity("GraduateApp.API.Models.EducationInfo", b =>
                {
                    b.HasOne("GraduateApp.API.Models.Student", "TcNavigation")
                        .WithMany("EducationInfos")
                        .HasForeignKey("Tc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GraduateApp.API.Models.University", "University")
                        .WithMany("EducationInfos")
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TcNavigation");

                    b.Navigation("University");
                });

            modelBuilder.Entity("GraduateApp.API.Models.LoginIdentity", b =>
                {
                    b.HasOne("GraduateApp.API.Models.Admin", "Admin")
                        .WithOne("LoginIdentity")
                        .HasForeignKey("GraduateApp.API.Models.LoginIdentity", "AdminId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GraduateApp.API.Models.Student", "Student")
                        .WithOne("LoginIdentity")
                        .HasForeignKey("GraduateApp.API.Models.LoginIdentity", "StudentTc")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Admin");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("GraduateApp.API.Models.PasswordResetToken", b =>
                {
                    b.HasOne("GraduateApp.API.Models.Admin", "Admin")
                        .WithMany("PasswordResetTokens")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GraduateApp.API.Models.Student", "TcNavigation")
                        .WithMany("PasswordResetTokens")
                        .HasForeignKey("Tc")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Admin");

                    b.Navigation("TcNavigation");
                });

            modelBuilder.Entity("GraduateApp.API.Models.Program", b =>
                {
                    b.HasOne("GraduateApp.API.Models.Institute", "Institute")
                        .WithMany("Programs")
                        .HasForeignKey("InstituteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Institute");
                });

            modelBuilder.Entity("GraduateApp.API.Models.ProgramOffering", b =>
                {
                    b.HasOne("GraduateApp.API.Models.Program", "Program")
                        .WithMany("Offerings")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Program");
                });

            modelBuilder.Entity("GraduateApp.API.Models.ProgramOfferingDocumentRequirement", b =>
                {
                    b.HasOne("GraduateApp.API.Models.ProgramOffering", "ProgramOffering")
                        .WithMany("DocumentRequirements")
                        .HasForeignKey("ProgramOfferingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProgramOffering");
                });

            modelBuilder.Entity("GraduateApp.API.Models.ProgramOfferingEvaluationCriterion", b =>
                {
                    b.HasOne("GraduateApp.API.Models.Exam", "Exam")
                        .WithMany()
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GraduateApp.API.Models.ProgramOffering", "ProgramOffering")
                        .WithMany("EvaluationCriteria")
                        .HasForeignKey("ProgramOfferingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Exam");

                    b.Navigation("ProgramOffering");
                });

            modelBuilder.Entity("GraduateApp.API.Models.ProgramOfferingExamRequirement", b =>
                {
                    b.HasOne("GraduateApp.API.Models.Exam", "Exam")
                        .WithMany("ProgramOfferingExamRequirements")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GraduateApp.API.Models.ProgramOffering", "ProgramOffering")
                        .WithMany("ExamRequirements")
                        .HasForeignKey("ProgramOfferingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");

                    b.Navigation("ProgramOffering");
                });

            modelBuilder.Entity("GraduateApp.API.Models.ReferenceLetter", b =>
                {
                    b.HasOne("GraduateApp.API.Models.Application", "Application")
                        .WithMany("ReferenceLetters")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("GraduateApp.API.Models.StudentExamScore", b =>
                {
                    b.HasOne("GraduateApp.API.Models.Exam", "Exam")
                        .WithMany("StudentExamScores")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GraduateApp.API.Models.Student", "TcNavigation")
                        .WithMany("StudentExamScores")
                        .HasForeignKey("Tc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");

                    b.Navigation("TcNavigation");
                });

            modelBuilder.Entity("GraduateApp.API.Models.SystemLog", b =>
                {
                    b.HasOne("GraduateApp.API.Models.Admin", "Admin")
                        .WithMany("SystemLogs")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GraduateApp.API.Models.Student", "TcNavigation")
                        .WithMany("SystemLogs")
                        .HasForeignKey("Tc")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Admin");

                    b.Navigation("TcNavigation");
                });

            modelBuilder.Entity("GraduateApp.API.Models.Admin", b =>
                {
                    b.Navigation("ApplicationStatusHistories");

                    b.Navigation("LoginIdentity");

                    b.Navigation("PasswordResetTokens");

                    b.Navigation("ReviewedApplicationDocuments");

                    b.Navigation("SystemLogs");
                });

            modelBuilder.Entity("GraduateApp.API.Models.Application", b =>
                {
                    b.Navigation("ApplicationStatusHistories");

                    b.Navigation("DocumentRequirementSnapshots");

                    b.Navigation("Documents");

                    b.Navigation("Evaluation");

                    b.Navigation("ReferenceLetters");

                    b.Navigation("ScoreSnapshots");
                });

            modelBuilder.Entity("GraduateApp.API.Models.ApplicationDocumentRequirementSnapshot", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("GraduateApp.API.Models.ApplicationEvaluation", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("GraduateApp.API.Models.Exam", b =>
                {
                    b.Navigation("ApplicationScoreSnapshots");

                    b.Navigation("ProgramOfferingExamRequirements");

                    b.Navigation("StudentExamScores");
                });

            modelBuilder.Entity("GraduateApp.API.Models.Institute", b =>
                {
                    b.Navigation("Programs");
                });

            modelBuilder.Entity("GraduateApp.API.Models.Program", b =>
                {
                    b.Navigation("Offerings");
                });

            modelBuilder.Entity("GraduateApp.API.Models.ProgramOffering", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("DocumentRequirements");

                    b.Navigation("EvaluationCriteria");

                    b.Navigation("ExamRequirements");
                });

            modelBuilder.Entity("GraduateApp.API.Models.ProgramOfferingDocumentRequirement", b =>
                {
                    b.Navigation("Snapshots");
                });

            modelBuilder.Entity("GraduateApp.API.Models.ProgramOfferingEvaluationCriterion", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("GraduateApp.API.Models.Student", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("EducationInfos");

                    b.Navigation("LoginIdentity");

                    b.Navigation("PasswordResetTokens");

                    b.Navigation("StudentExamScores");

                    b.Navigation("SystemLogs");
                });

            modelBuilder.Entity("GraduateApp.API.Models.University", b =>
                {
                    b.Navigation("EducationInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
